stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Job Building has been started"

test-job:
  stage: test
  script:
    - echo “If the built job completed properly, test the build"

deploy-job:
  stage: deploy
  script:
    - echo “If Testing job completed successfully, then deployment will start”
