---
- hosts: all
  become: yes

  tasks:

    - name: Install system updates for RHEL operating systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"

